const dataArr = [
    {  
        id: 'item1',
        img: '/img/content/tshirt.png',
        price: 522,
        sale: 783,
        title: 'Футболка UZcotton мужская',
        color: 'белый',
        size: 56,
        storage: 'Коледино WB',
        company: 'OOO Вайлдберриз',
        tooltip: 'OOO "ВАЙЛДБЕРРИЗ"',
        ogrn: '1067746062449',
        addr: '142181, Московская область, д Коледино, тер. Индустриальный Парк Коледино, д. 6 стр. 1',
        count: 1,
        reminder: 3,
        storage1: 3,
        storage2: 0,
    },
    { 
        id: 'item2',
        img: '/img/content/case.png',
        price: '2 100 047',
        sale: '3 150 070',
        title: 'Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe',
        color: 'прозрачный',
        size: null,
        storage: 'Коледино WB',
        company: 'OOO Мегапрофстиль',
        tooltip: 'OOO «МЕГАПРОФСТИЛЬ»',
        ogrn: '5167746237148',
        addr: '129337, Москва, улица Красная Сосна, 2, корпус 1, стр. 1, помещение 2, офис 34',
        count: 200,
        reminder: 203,
        storage1: 184,
        storage2: 19,
    },
    { 
        id: 'item3',
        img: '/img/content/pencils.png',
        price: 494,
        sale: 741,
        title: 'Карандаши цветные Faber-Castell "Замок", набор 24 цвета, заточенные, шестигранные, Faber-Castell',
        color: null,
        size: null,
        storage: 'Коледино WB',
        company: 'OOO Вайлдберриз',
        tooltip: 'OOO "ВАЙЛДБЕРРИЗ"',
        ogrn: '1067746062449',
        addr: '142181, Московская область, д Коледино, тер. Индустриальный Парк Коледино, д. 6 стр. 1',
        count: 2,
        reminder: 4,
        storage1: 4,
        storage2: 0,
    }
];